### PR TITLE
Added EfficientNet

### PR DESCRIPTION
**Pull request by dikshantsagar**

### CODE REVIEW

**Comment by abhineet123** [comment]
Hello Dikshant, Thanks for your contributions ! 
I only like to add PDFs to the repo when I've read the paper in detail and can also add it to the [papers section](https://github.com/abhineet123/Deep-Learning-for-Tracking-and-Detection#paper_s_) along with notes. If you've read this paper, please add an entry there with notes in the [static_detection/notes](https://github.com/abhineet123/Deep-Learning-for-Tracking-and-Detection/tree/master/static_detection/notes) folder.
If not, but you think that it is an interesting paper with available code, please add an entry in the code section instead.

**Comment by dikshantsagar** [comment]
Sure, I've got the notes. I'll add them too

**Comment by dikshantsagar** [comment]
It should follow the same format, right?

**Comment by abhineet123** [comment]
Yes

**Comment by dikshantsagar** [comment]
added Efficient Notes, you can merge.

**Comment by dikshantsagar** [comment]
added EfficientNet notes, you can merge

**Comment by abhineet123** [comment]
Thanks!
Two more things:
1. EfficientNet (and its notes) will go into deep_learning/efficient folder and EfficientDet will remain in static_detection
2. Can you also add entries to the respective subsections of the papers section of the readme with links to PDF, notes and code ? Please follow formatting of existing entries.

**Comment by dikshantsagar** [comment]
Done

**Pull request merged**
